[package]
name = "ecma_temporal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
parse-zoneinfo = { version = "0.3" }
phf_codegen = { version = "0.10", default-features = false }
